name: 01-building-blocks
on:
  - workflow_dispatch

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello!
        run: echo "Hello, World!"

  echo-goodbye:
    runs-on:  ubuntu-latest
    steps:
      - name: Failed steps
        run: echo "i may or maynot fail"

      - name: Say goodbye
        run: echo "goodbye!"
