name: 03-workflow-runners
on: push

jobs:
  ubuntu-echo:
      runs-on: ubuntu-latest
      steps:
        - name: show OS
          run: echo "This job is runnign on an Ubuntu runner"

  windows-echo:
      runs-on: windows-latest
      steps:
        - name: Show OS
          run: "This job is running no a windows runner"
    
  macos-latest:
      runs-on: macos-latest
      steps:
        - name: Show OS
          run: "This job is runnign on a MacOS runner"