name: 03-workflow-runners
on: push

jobs:
  ubuntu-echo:
      runs-on: ubuntu-latest
      steps:
        - name: show OS
          run: echo "This job is runnign on an Ubuntu runner"

  windows-echo:
      runs-on: windows-latest
      steps:
        - name: Show OS
          shell: bash
          run: echo "this is ${{github.RUNNER_OS}}"
    
