name: 04-using-actions
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: Setup node
        run: |
              cd ../..
              cd react-app
              npm ci
        
