name: 05-1-filters-activity-types
on: 
  workflow_dispatch: 
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main"