name: 06-contexts.yaml
on: 
  push:
  workflow_dispatch: 

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
            echo "Event name: ${{github.Event}}"
            echo "Event name: ${{github.ref}}"
            echo "Event name: ${{github.sha}}"
            echo "Event name: ${{github.actor}}"
            echo "Event name: ${{github.workflow}}"
            echo "Event name: ${{github.run_id}}"
            echo "Event name: ${{github.run_number}}"

      - name: Retrieve Variable
        run: echo ${{vars.MY_VAR}}