name: 06-contexts.yaml
on: 
  push:
  workflow_dispatch: 

run-name: 06- Context | Debug - ${{inputs.debug}}

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
            echo "Event Name ${{github.event_name}}"
            echo "Event Name ${{github.ref}}"
            echo "Event Name ${{github.sha}}"
            echo "Event Name ${{github.actor}}"
            echo "Event Name ${{github.workflow}}"
            echo "Event Name ${{github.run_id}}"
            echo "Event Name ${{github.run_number}}"
      
      - name: Retrieve Variable
        run: echo "${{vars.MY_VAR}}""


