name: 06-contexts
on:
  push:
  workflow_dispatch: 

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
             echo "Event name: ${{github.event}}"
             echo "Ref: ${{github.ref}}"
             echo "SHA: ${{github.sha}}"
             echo "Actor ${{github.workflow}}"
             echo "Run ID: ${{github.run_id}}"
             echo "Run number: ${{github.run_number}}"
            
      - name: Retrieve variable
        run: echo "${{vars.MY_VAR}}"
