name: 06-contexts.yaml
on: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false

run-name: 06- Context | Debug - ${{inputs.debug}}

env:
  MY_WORKFLOW_VAR : 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
            echo "Event Name ${{github.event_name}}"
            echo "Event Name ${{github.ref}}"
            echo "Event Name ${{github.sha}}"
            echo "Event Name ${{github.actor}}"
            echo "Event Name ${{github.workflow}}"
            echo "Event Name ${{github.run_id}}"
            echo "Event Name ${{github.run_number}}"
      
      - name: Retrieve Variable
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
            "workflow env: ${{env.MY_WORKFLOW_VAR}}"
            "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"


