name: 07-expressions
on: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false

run-name: 07 - Using Expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: print startup data
        if: inputs.debug == 'true'
        run: |
              echo "Triggered by: ${{github.event_name}}"
              echo "Triggered by: ${{github.ref}}"
              echo "Triggered by: ${{github.sha}}"
              echo "Triggered by: ${{runner.os}}"

      - name: Print when Triggered from main
        if: github.ref == 'main'
        run: echo "I was triggered from main"

      - name: Greeting
        run: echo "Hello World"
