name: 12-Working with outputs
on: 
  workflow_dispatch: 
    inputs:
      build-statue:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    outputs:
      build-status: ${{steps.build.outputs.status}}
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: echo "status= ${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        if: ${{ needs.build.outputs.build-status == 'success'}}
        run: echo "Deploying"