name: Working with Matrices
on: 
  push

jobs:
  backwards-compatability:
    name: ${{matrix.os}}-${{matrix.node-version}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 21.x
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - node-version: 16.x
            os: ubuntu-latest

          - node-version: 21.x
            os: ubuntu-latest
            tag: experimental


    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1

      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{matrix.os}} and ${{matrix.node-version}}"
          sleep 10

  include-example:
    runs-on: ubuntu-latest
    name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
    strategy:
      matrix:
        color: [red,green]
        shape: [circle,square]
        size: [small,large]
      
        include:
          - color : red
            shape: triangle
          
          - opacity: 50
            color: red 

          - opacity: 75
            color: circle
          
          - opacity: 100
            color: triangle
    steps:
      - name: Dummy step
        run: echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}"