name: Working with Matrices
on: 
  push

jobs:
  backwards-compatability:
    name: ${{matrix.os}}-${{matrix.node-version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 21.x
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - node-version: 16.x
            os: ubuntu-latest

          - node-version: 21.x
            os: ubuntu-latest


    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Perform some tests
        run: echo "Running tests on OS ${{matrix.os}} and ${{matrix.node-version}}"