name: 16-environment
on: 
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

run-name: 16- Working with Environments | env - ${{inputs.target-env}}

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
      my-env-value: MY_ENV_VALUE

    steps:
      - name: Echo vars
        run: echo " Environment variable ${{vars.my-env-value}}"